# Generated by Django 4.1.1 on 2022-09-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_empleado_ruc_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaPrestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capital', models.FloatField(null=True)),
                ('motivo', models.CharField(blank=True, choices=[('P', 'PERSONAL'), ('S', 'SALUD')], default='P', max_length=1, null=True)),
                ('cuotas', models.IntegerField(null=True)),
                ('interes', models.FloatField(null=True)),
                ('capitaltotal', models.FloatField(null=True)),
                ('totalinteres', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empresas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
