# Generated by Django 4.1.1 on 2022-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_facturaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ruc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
