# Generated by Django 4.1.1 on 2022-09-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_alter_empresas_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefonos',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='motivo',
            field=models.CharField(blank=True, choices=[('P', 'Personal'), ('S', 'Salud')], default='P', max_length=1, null=True),
        ),
    ]
