# Generated by Django 4.1.1 on 2022-09-25 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_alter_empleado_telefonos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaprestamo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
