# Generated by Django 4.1.1 on 2022-09-25 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0006_facturaprestamo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now, null=True)),
                ('precio', models.FloatField(null=True)),
                ('cuotas', models.IntegerField(null=True)),
                ('valorcuota', models.FloatField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empresas')),
            ],
            options={
                'verbose_name': 'Descuentos',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['id'],
            },
        ),
    ]
