# Generated by Django 4.1.1 on 2022-09-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_descuentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaprestamo',
            name='capitaltotal',
        ),
    ]
