# Generated by Django 4.1.1 on 2022-09-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0009_alter_facturaprestamo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaprestamo',
            name='fechainicio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
