# Generated by Django 4.1.1 on 2022-09-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0011_alter_facturaprestamo_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaprestamo',
            name='fechainicio',
            field=models.DateField(null=True),
        ),
    ]
