# Generated by Django 4.1.1 on 2022-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0012_alter_facturaprestamo_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos',
            name='fechainicio',
            field=models.DateField(null=True),
        ),
    ]
