# Generated by Django 4.1.1 on 2022-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0013_descuentos_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='valorcuota',
            field=models.FloatField(default=0, null=True),
        ),
    ]
