# Generated by Django 4.1.1 on 2022-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0014_alter_descuentos_valorcuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaprestamo',
            name='capital',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='totalinteres',
            field=models.FloatField(default=0, null=True),
        ),
    ]
