# Generated by Django 4.1.1 on 2022-09-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0015_alter_facturaprestamo_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empleado', unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.empleado', unique=True),
        ),
    ]
