# Generated by Django 4.1.1 on 2022-10-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0018_alter_facturaprestamo_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.empleado', unique=True),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.empresas'),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.empleado', unique=True),
        ),
        migrations.AlterField(
            model_name='facturaprestamo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.empresas'),
        ),
    ]
